export const TRANSITION_IDS = {
  READY_FOR_QA: "91",
  TO_CODE_REVIEW: "61",
  TO_RELEASED: "131",
};

export const STATUS_IDS = {
  IN_DEVELOPMENT: "10489",
  READY_FOR_CODE_REVIEW: "10019",
  IN_CODE_REVIEW: "10020",
};
